openapi: "3.0.2"
info:
  title: "plm backend"
  version: "1.00"
servers:
  - url: http://localhost:8085/api
paths:
  /login:
    post:
      summary: Вход в систему
      operationId: login
      tags:
        - LOGIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginDto"
      responses:
        200:
          description: Пустой ответ

  /logout:
    post:
      summary: Выход из системы
      operationId: logout
      tags:
        - LOGIN
      responses:
        200:
          description: Пустой ответ
  /admin/plmTree:
    get:
      summary: Выборка списка ролей
      operationId: getPlmTree
      tags:
        - ADMIN
      responses:
        200:
          description: Список ролей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/plmTreeDto"
components:
  schemas:
    plmTreeDto:
      type: array
      description: Иерархическое дерево
      items:
        $ref: "#/components/schemas/plm"
    plm:
      type: object
      description: Строка справочника
      properties:
        sPk:
          type: integer
          format: int64
          description: Идентификатор записи
          example: 1
        sParentid:
          type: integer
          format: int64
          description: Идентификатор вышестоящего узла
          example: 1
        name:
          type: string
          description: Наименование
          example: Наименование 1
        description:
          type: string
          description: Описание
          example: Описание 1
        className:
          type: string
          description: Наименование класса
          example: Наименование класса 1
        level:
          type: integer
          format: int64
          description: Уровень вложенности узла
          example: 1
        path:
          type: string
          description: Полный путь
          example: Полный путь 1
#    refRecordInDto:
#      type: object
#      description: Строка справочника
#      properties:
#        name:
#          type: string
#          description: Наименование
#          example: Наименование 1
#    roleFullViewDto:
#      type: object
#      description: Данные по роли
#      properties:
#        id:
#          type: integer
#          format: int64
#          description: Идентификатор записи
#          example: 1
#        name:
#          type: string
#          description: Наименование роли
#          example: ADMIN
    loginDto:
      type: object
      description: Данные для входа в систему
      properties:
        username:
          type: string
          description: Имя пользователя
          example: ADMIN
        password:
          type: string
          description: Наименование
          example: ADMIN

